# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 08:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pic.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licensename', models.CharField(max_length=120, verbose_name='证件类型')),
                ('licensetypeid', models.IntegerField(verbose_name='证件类型ID')),
            ],
            options={
                'verbose_name': '证件类型',
                'verbose_name_plural': '证件类型',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200, verbose_name='公司名称')),
                ('companyid', models.IntegerField(verbose_name='公司ERPID')),
                ('companytype', models.CharField(choices=[('供应商', '供应商'), ('客户', '客户'), ('其它', '其它')], default='供应商', max_length=10, verbose_name='公司类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.CharField(choices=[('正式', '正式'), ('作废', '作废')], default='正式', max_length=10, verbose_name='状态')),
            ],
            options={
                'verbose_name': '公司信息',
                'verbose_name_plural': '公司信息',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyname', models.CharField(max_length=200, verbose_name='公司名称')),
                ('companyid', models.IntegerField(verbose_name='公司ID')),
                ('ziplink', models.FileField(upload_to=pic.models.get_zip_path, verbose_name='zip文档链接')),
                ('pdflink', models.FileField(upload_to=pic.models.get_pdf_path, verbose_name='pdf文档链接')),
                ('downloads', models.IntegerField(default=0, verbose_name='下载次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('create_date', models.DateField(auto_now_add=True, verbose_name='创建日期')),
                ('status', models.CharField(choices=[('正式', '正式'), ('作废', '作废')], default='正式', max_length=10, verbose_name='状态')),
                ('cate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.Cate', verbose_name='证件类型')),
            ],
            options={
                'verbose_name': '电子档案',
                'verbose_name_plural': '电子档案',
            },
        ),
    ]
