# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pic',
            name='companyid',
        ),
        migrations.AlterField(
            model_name='pic',
            name='companyname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pic.Company', verbose_name='公司名称'),
        ),
    ]
