# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_auto_20180412_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pdflink',
            field=models.FileField(null=True, upload_to='photos/%Y/%m/%d', verbose_name='pdf文档链接'),
        ),
        migrations.AlterField(
            model_name='pic',
            name='ziplink',
            field=models.FileField(upload_to='photos/%Y/%m/%d', verbose_name='zip文档链接'),
        ),
    ]
