# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-13 01:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0003_auto_20180413_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pic',
            name='pdflink',
            field=models.FileField(blank=True, null=True, upload_to='photos/%Y/%m/%d', verbose_name='pdf文档链接'),
        ),
    ]
